### ISSUE TITLE
Question (not issue)

### ISSUE THREAD

**Issue by shaulnaim** [ngneat/from-event#1]
hi @NetanelBasal, you mentioned 
"Have fun, and don't forget to unsubscribe. You can do it with until-destroy."

I tried using the ngneat untildestroyed decorator but when I tried to test the component (using spectator and jest) it kept giving me errors that the unsubscribe didn't work and it only stopped when I gave up on @untilDestroyed and back to unsubscribe on ngOnDestroy. 
are you familiar with this behavior? how should the test be written?
Thanks, you are doing great work.

**Comment by NetanelBasal** [comment]
until-destroy works only with Ivy. I'll remove this part. Thanks.
