### ISSUE TITLE
Support bind event outsideAngular

### ISSUE THREAD

**Issue by xiaoxiangmoe** [ngneat/from-event#2]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

---
 Can we bind event in `this.ngZone.runOutsideAngular()`?

**Comment by NetanelBasal** [comment]
No, we can't. First, we need access to `ngZone`. Second, you need to run it outside when you actually `subscribed`.
